title: "Kevin Armstrong II Engineering Portfolio"
description: "University of California, Berkeley<br>Mechanical Engineering ’28"
logo: /assets/4headshot.JPG
show_downloads: false
theme: jekyll-theme-primer
